steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/jio-big-data-poc/hello-repo', '.']
    id: 'Build and push Docker image'
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/jio-big-data-poc/hello-repo']
    id: 'Push Docker image'
